# Default terminal
set-option -g default-terminal "xterm-256color"

# Use vim key bindings
set-option -g mode-keys vi
set-option -g status-keys vi

# Turn the mouse on
set-option -g mouse on

# Time in milliseconds for which tmux waits after an escape
set-option -g escape-time 0

# Enable supported focus events
set-option -g focus-events on

# History settings
set-option -g history-limit 10000
set-option -g history-file ~/.tmux/tmuxhistory

# Activity
set-option -g monitor-activity on
set-option -g visual-activity off

# Start window index at 1
set-option -g base-index 1

# Start pane index at 1
set-option -g pane-base-index 1

# Rename window to reflect current program
set-option -g -w automatic-rename on

# Renumber windows when one is closed
set-option -g renumber-windows on

# No bells at all
set-option -g bell-action none

# Enable RGB color if running in xterm
set-option -g -a terminal-overrides ",xterm-256color:Tc"

# Override Home and End key
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Reload configuration
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# Split pane with same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Select
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Copy
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Paste
bind-key p paste-buffer -s ""
bind-key P choose-buffer "paste-buffer -b '%%' -s ''"

# Kill session
bind-key q confirm-before -p "kill-session #S? (y/n)" kill-session

# Mode
set-option -g mode-style bg=brightblack,fg=default

# Status
set-option -g status on
set-option -g status-position top

# Status update interval
set-option -g status-interval 5

# Basic status bar colors
set-option -g status-style bg=default,fg=white

# Left side of status bar
set-option -g status-left-length 40
set-option -g status-left "#[fg=brightwhite,bg=brightblack] #S #[fg=default,bg=default] "

# Window status
set-option -g window-status-format "#[fg=white,bg=brightblack] #I #[fg=white,bg=#363636] #W "
set-option -g window-status-current-format "#[fg=brightwhite,bg=green] #I #[fg=brightwhite,bg=blue] #W "
set-option -g window-status-separator " "
set-option -g status-justify left

# Right side of status bar
set-option -g status-right-length 40
set-option -g status-right " #[fg=brightwhite,bg=#363636] %a, %d %b %H:%M #[fg=brightwhite,bg=brightblack] #(whoami)@#h "

# Pane border
set-option -g pane-border-style bg=default,fg=brightblack
set-option -g pane-active-border-style bg=default,fg=white

# Pane number indicator
set-option -g display-panes-colour brightblack
set-option -g display-panes-active-colour brightwhite

# Clock mode
set-option -g clock-mode-colour white
set-option -g clock-mode-style 24

# Message
set-option -g message-style bg=default,fg=default
